### ISSUE TITLE
Wish this could have support for genre based view like the web player

### ISSUE THREAD

**Issue by linnabraham** [Codrax/iBroadcast-For-Linux#1]
I decided to try the app hoping for this feature. Currently I use plattenalbum which is an mpd client as my music player. However the view are limited to Artists etc. Seeing the iBroadcast player which can play music with Genre I was looking for a native app and came across yours. The app looks really nice. However this feature seems missing. Is it planned or in your consideration? If not please consider it.

**Comment by Codrax** [comment]
I could certainly try to implement this. When I build iBroadcast fro Linux, I started from the ground up based on my already existing project, iBroadcast for Windows. In this process, I build the app to be as dynamic as possible. So I'll try adding this today. I'll update you on this matter!

**Comment by Codrax** [comment]
![image](https://github.com/Codrax/iBroadcast-For-Linux/assets/68193064/a558313e-959f-49a9-80db-3ed567f7fb82)

**Comment by Codrax** [comment]
This feature was successfully implemented in iBroadcast for Linux version 1.1.0

Thanks for the suggestion!

**Comment by linnabraham** [comment]
Thank you!!... Thanks for the very quick response. I can't believe I got a resolution this fast. Let me try to install the new version.

**Comment by Codrax** [comment]
No problem! :)
Let me know If you encounter any issues whatsoever!
